<?php

/**
 * ARK Item Entity
 *
 * This file is automatically generated as part of ARK, the Archaeological Recording Kit.
 */

namespace ARK\Entity\Actor;

use ARK\Entity\Actor;

class Museum extends Actor
{
}
