<?php

/**
 * ARK Item Entity.
 *
 * This file is automatically generated as part of ARK, the Archaeological Recording Kit.
 */

namespace DIME\Entity;

use ARK\Security\Actor;

class Museum extends Actor
{
}
