<?php

/**
 * ARK ORM Item Entity Generator
 *
 * Copyright (C) 2017  L - P : Heritage LLP.
 *
 * This file is part of ARK, the Archaeological Recording Kit.
 *
 * ARK is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ARK is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ARK.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author     John Layt <j.layt@lparchaeology.com>
 * @copyright  2017 L - P : Heritage LLP.
 * @license    GPL-3.0+
 * @see        http://ark.lparchaeology.com/
 * @since      2.0
 * @php        >=5.6, >=7.0
 */

namespace ARK\ORM;

use ARK\Service;
use ARK\Model\VersionTrait;
use ARK\ORM\ClassMetadataBuilder;
use Doctrine\Common\Persistence\Mapping\ClassMetadata;
use Doctrine\Common\Persistence\Mapping\Driver\MappingDriver;
use Doctrine\Common\Persistence\Mapping\MappingException;
use Doctrine\ORM\Mapping\ClassMetadataInfo;
use Doctrine\ORM\Tools\EntityGenerator;

class ItemEntityGenerator implements EntityGenerator
{
    protected static $classTemplate =
'<?php

/**
 * <entityClassName> ORM Entity
 *
 * This file is automatically generated as part of ARK, the Archaeological Recording Kit.
 */

<namespace>
use ARK\Model\Item;
use ARK\Model\ItemTrait;
<useStatement>
<entityAnnotation>
<entityClassName> implements Item
{
<spaces>use ItemTrait;
<entityBody>
}
';

protected static $constructorMethodTemplate =
'/**
* Constructor
*/
public function __construct($schema)
{
<spaces>$this->schma = $schema;
<spaces><collections>
}
';

    public function __construct()
    {
        parent::__construct();
        $this->setRegenerateEntityIfExists(true);
    }
}
