<?php

/**
 * ARK Item Entity.
 *
 * This file is automatically generated as part of ARK, the Archaeological Recording Kit.
 */

namespace ARK\File;

use ARK\Service;

class Image extends File
{
    public function sourcePath(string $preset = null) : string
    {
        $paramaters = [];
        if ($preset) {
            $paramaters['p'] = $preset;
        }
        $path = Service::imagePath('file', $this->id(), $paramaters);
        return $path;
    }
}
