<?php

/**
 * ARK Item Entity.
 *
 * This file is automatically generated as part of ARK, the Archaeological Recording Kit.
 */

namespace ARK\File;

use ARK\Service;

class Image extends File
{
    public function sourcePath(string $preset = null) : string
    {
        $path = Service::path('img', ['image' => $this->id()]);
        if ($preset) {
            return $path.'?p='.$preset;
        }
        return $path;
    }
}
